version: "3"

services:

  nuxt:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: ./front/
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
    container_name: nuxtmay2021_nuxt_1

  node:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: ./backend/
    restart: always
    ports:
      - "5000:5000"
    command:
      "npm run start"
    container_name: nuxtmay2021_node_1

  nginx:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
    container_name: nuxtmay2021_nginx_1
