version: "3"

services:
  nuxt:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
    container_name: nuxtmay2021_nuxt_1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
    container_name: nuxtmay2021_nginx_1
